apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: samba-credentials
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: 2h
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
    namespace: external-secrets
  target:
    name: samba-shared-credentials
    creationPolicy: Owner
  data:
    - secretKey: GUEST_PASSWORD
      remoteRef:
        key: /samba/GUEST_PASSWORD