apiVersion: apps/v1
kind: Deployment
metadata:
  name: byparr
  namespace: {{ .Values.namespace }}
  labels:
    app: byparr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: byparr
  template:
    metadata:
      name: byparr
      labels:
        app: byparr
    spec:
      containers:
        - name: byparr
          image: {{ .Values.byparr.image }}
          startupProbe:
            httpGet:
              port: 8191
              path: /health
            periodSeconds: 20
            initialDelaySeconds: 20
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              port: 8191
              path: /health
            periodSeconds: 3600
            initialDelaySeconds: 100
            timeoutSeconds: 15
          resources:
            limits:
              cpu: "1000m"
              memory: "4000Mi"
          ports:
            - containerPort: 8191
              protocol: TCP