apiVersion: v1
kind: Service
metadata:
  name: qui
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: qui
  ports:
    - protocol: TCP
      port: 7476
      targetPort: 7476
  type: ClusterIP
